from __future__ import annotations

import engine as en

from . import t01_six_five_two_one as t01
from . import t02_runway_aurora as t02
from . import t03_gravity_has_a_chorus as t03
from . import t04_all_the_lights_arrive_late as t04
from . import t05_bright_matter as t05

SPECS: tuple[en.TrackSpec, ...] = (
    en.TrackSpec(
        1,
        "Six-Five-Two-One",
        "01 - Six-Five-Two-One.mid",
        2026071101,
        132.0,
        584.0,
        t01.build,
        t01.oracles,
        "upbeat progressive electronic pop with a 360-degree steel-pan orbit",
        "The vi-V-ii-I sequence is counted into existence, then survives two drops and a two-semitone finale lift.",
        (260.0, 310.0),
        2800,
        16,
        9,
        5,
        ("6521", "build-drop", "orbit", "key-lift"),
    ),
    en.TrackSpec(
        2,
        "Runway Aurora",
        "02 - Runway Aurora.mid",
        2026071102,
        126.0,
        548.0,
        t02.build,
        t02.oracles,
        "neon synth-rock with hocketed runway lights and bending guitar",
        "Alternating lamps become propulsion; a half-time cloud deck gives way to a faster aurora-sized second launch.",
        (255.0, 305.0),
        3000,
        16,
        8,
        5,
        ("6521", "synth-rock", "guitar", "acceleration"),
    ),
    en.TrackSpec(
        3,
        "Gravity Has a Chorus",
        "03 - Gravity Has a Chorus.mid",
        2026071103,
        140.0,
        588.0,
        t03.build,
        t03.oracles,
        "odd-meter electronic anthem for two choirs and cathedral organ",
        "Seven-beat launch vectors repeatedly fall into four-square gravity until a full organ and massed chorus crown the finale.",
        (270.0, 330.0),
        2600,
        16,
        8,
        5,
        ("6521", "odd-meter", "choir", "organ"),
    ),
    en.TrackSpec(
        4,
        "All the Lights Arrive Late",
        "04 - All the Lights Arrive Late.mid",
        2026071104,
        118.0,
        544.0,
        t04.build,
        t04.oracles,
        "luminous mallet-pop with echo throws and a deliberately withheld kick",
        "The hook lands before the floor does: the false drop holds back its kick, then the whole night skyline arrives at once.",
        (260.0, 320.0),
        2700,
        16,
        8,
        5,
        ("6521", "fake-drop", "mallets", "echo"),
    ),
    en.TrackSpec(
        5,
        "Bright Matter (Everything at Once)",
        "05 - Bright Matter (Everything at Once).mid",
        2026071105,
        128.0,
        688.0,
        t05.build,
        t05.oracles,
        "maximalist progressive electronic finale with four-hook counterpoint",
        "All four earlier themes enter simultaneously over a circling transient orbit, organ swell, choir, guitar bends, and a final key lift.",
        (315.0, 380.0),
        3900,
        16,
        9,
        5,
        ("6521", "finale", "counterpoint", "orbit", "key-lift"),
    ),
)
