//! Embedded MIT MuseScore_General grand-piano samples, MF tier (GM 1 Bright Acoustic alternate, CC0=2).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through `ferrosintesis`.
//! Licence/provenance: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 25;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "musescoregrand_A2.wav",
        include_bytes!("../samples/musescoregrand_A2.wav"),
    ),
    (
        "musescoregrand_A3.wav",
        include_bytes!("../samples/musescoregrand_A3.wav"),
    ),
    (
        "musescoregrand_A4.wav",
        include_bytes!("../samples/musescoregrand_A4.wav"),
    ),
    (
        "musescoregrand_B1.wav",
        include_bytes!("../samples/musescoregrand_B1.wav"),
    ),
    (
        "musescoregrand_B2.wav",
        include_bytes!("../samples/musescoregrand_B2.wav"),
    ),
    (
        "musescoregrand_B3.wav",
        include_bytes!("../samples/musescoregrand_B3.wav"),
    ),
    (
        "musescoregrand_B4.wav",
        include_bytes!("../samples/musescoregrand_B4.wav"),
    ),
    (
        "musescoregrand_B5.wav",
        include_bytes!("../samples/musescoregrand_B5.wav"),
    ),
    (
        "musescoregrand_C#6.wav",
        include_bytes!("../samples/musescoregrand_C#6.wav"),
    ),
    (
        "musescoregrand_C3.wav",
        include_bytes!("../samples/musescoregrand_C3.wav"),
    ),
    (
        "musescoregrand_C4.wav",
        include_bytes!("../samples/musescoregrand_C4.wav"),
    ),
    (
        "musescoregrand_C5.wav",
        include_bytes!("../samples/musescoregrand_C5.wav"),
    ),
    (
        "musescoregrand_D#6.wav",
        include_bytes!("../samples/musescoregrand_D#6.wav"),
    ),
    (
        "musescoregrand_D2.wav",
        include_bytes!("../samples/musescoregrand_D2.wav"),
    ),
    (
        "musescoregrand_D3.wav",
        include_bytes!("../samples/musescoregrand_D3.wav"),
    ),
    (
        "musescoregrand_D4.wav",
        include_bytes!("../samples/musescoregrand_D4.wav"),
    ),
    (
        "musescoregrand_E2.wav",
        include_bytes!("../samples/musescoregrand_E2.wav"),
    ),
    (
        "musescoregrand_E3.wav",
        include_bytes!("../samples/musescoregrand_E3.wav"),
    ),
    (
        "musescoregrand_E4.wav",
        include_bytes!("../samples/musescoregrand_E4.wav"),
    ),
    (
        "musescoregrand_E5.wav",
        include_bytes!("../samples/musescoregrand_E5.wav"),
    ),
    (
        "musescoregrand_G#5.wav",
        include_bytes!("../samples/musescoregrand_G#5.wav"),
    ),
    (
        "musescoregrand_G2.wav",
        include_bytes!("../samples/musescoregrand_G2.wav"),
    ),
    (
        "musescoregrand_G3.wav",
        include_bytes!("../samples/musescoregrand_G3.wav"),
    ),
    (
        "musescoregrand_G4.wav",
        include_bytes!("../samples/musescoregrand_G4.wav"),
    ),
    (
        "musescoregrand_G5.wav",
        include_bytes!("../samples/musescoregrand_G5.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 3326200;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
