//! Embedded CC-BY 3.0 darkened Salamander grand samples (GM 0 acoustic-grand alternate, CC0=5).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.flac`; consumers normally reach it through `ferrosintesis`.
//! Licence/provenance: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of sample files embedded in this package.
pub const FILE_COUNT: usize = 54;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "darkgrand_C2_f.flac",
        include_bytes!("../samples/darkgrand_C2_f.flac"),
    ),
    (
        "darkgrand_C2_f_rr2.flac",
        include_bytes!("../samples/darkgrand_C2_f_rr2.flac"),
    ),
    (
        "darkgrand_C2_mf.flac",
        include_bytes!("../samples/darkgrand_C2_mf.flac"),
    ),
    (
        "darkgrand_C2_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_C2_mf_rr2.flac"),
    ),
    (
        "darkgrand_C2_pp.flac",
        include_bytes!("../samples/darkgrand_C2_pp.flac"),
    ),
    (
        "darkgrand_C2_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_C2_pp_rr2.flac"),
    ),
    (
        "darkgrand_C3_f.flac",
        include_bytes!("../samples/darkgrand_C3_f.flac"),
    ),
    (
        "darkgrand_C3_f_rr2.flac",
        include_bytes!("../samples/darkgrand_C3_f_rr2.flac"),
    ),
    (
        "darkgrand_C3_mf.flac",
        include_bytes!("../samples/darkgrand_C3_mf.flac"),
    ),
    (
        "darkgrand_C3_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_C3_mf_rr2.flac"),
    ),
    (
        "darkgrand_C3_pp.flac",
        include_bytes!("../samples/darkgrand_C3_pp.flac"),
    ),
    (
        "darkgrand_C3_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_C3_pp_rr2.flac"),
    ),
    (
        "darkgrand_C4_f.flac",
        include_bytes!("../samples/darkgrand_C4_f.flac"),
    ),
    (
        "darkgrand_C4_f_rr2.flac",
        include_bytes!("../samples/darkgrand_C4_f_rr2.flac"),
    ),
    (
        "darkgrand_C4_mf.flac",
        include_bytes!("../samples/darkgrand_C4_mf.flac"),
    ),
    (
        "darkgrand_C4_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_C4_mf_rr2.flac"),
    ),
    (
        "darkgrand_C4_pp.flac",
        include_bytes!("../samples/darkgrand_C4_pp.flac"),
    ),
    (
        "darkgrand_C4_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_C4_pp_rr2.flac"),
    ),
    (
        "darkgrand_C5_f.flac",
        include_bytes!("../samples/darkgrand_C5_f.flac"),
    ),
    (
        "darkgrand_C5_f_rr2.flac",
        include_bytes!("../samples/darkgrand_C5_f_rr2.flac"),
    ),
    (
        "darkgrand_C5_mf.flac",
        include_bytes!("../samples/darkgrand_C5_mf.flac"),
    ),
    (
        "darkgrand_C5_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_C5_mf_rr2.flac"),
    ),
    (
        "darkgrand_C5_pp.flac",
        include_bytes!("../samples/darkgrand_C5_pp.flac"),
    ),
    (
        "darkgrand_C5_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_C5_pp_rr2.flac"),
    ),
    (
        "darkgrand_C6_f.flac",
        include_bytes!("../samples/darkgrand_C6_f.flac"),
    ),
    (
        "darkgrand_C6_f_rr2.flac",
        include_bytes!("../samples/darkgrand_C6_f_rr2.flac"),
    ),
    (
        "darkgrand_C6_mf.flac",
        include_bytes!("../samples/darkgrand_C6_mf.flac"),
    ),
    (
        "darkgrand_C6_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_C6_mf_rr2.flac"),
    ),
    (
        "darkgrand_C6_pp.flac",
        include_bytes!("../samples/darkgrand_C6_pp.flac"),
    ),
    (
        "darkgrand_C6_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_C6_pp_rr2.flac"),
    ),
    (
        "darkgrand_F#2_f.flac",
        include_bytes!("../samples/darkgrand_F#2_f.flac"),
    ),
    (
        "darkgrand_F#2_f_rr2.flac",
        include_bytes!("../samples/darkgrand_F#2_f_rr2.flac"),
    ),
    (
        "darkgrand_F#2_mf.flac",
        include_bytes!("../samples/darkgrand_F#2_mf.flac"),
    ),
    (
        "darkgrand_F#2_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_F#2_mf_rr2.flac"),
    ),
    (
        "darkgrand_F#2_pp.flac",
        include_bytes!("../samples/darkgrand_F#2_pp.flac"),
    ),
    (
        "darkgrand_F#2_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_F#2_pp_rr2.flac"),
    ),
    (
        "darkgrand_F#3_f.flac",
        include_bytes!("../samples/darkgrand_F#3_f.flac"),
    ),
    (
        "darkgrand_F#3_f_rr2.flac",
        include_bytes!("../samples/darkgrand_F#3_f_rr2.flac"),
    ),
    (
        "darkgrand_F#3_mf.flac",
        include_bytes!("../samples/darkgrand_F#3_mf.flac"),
    ),
    (
        "darkgrand_F#3_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_F#3_mf_rr2.flac"),
    ),
    (
        "darkgrand_F#3_pp.flac",
        include_bytes!("../samples/darkgrand_F#3_pp.flac"),
    ),
    (
        "darkgrand_F#3_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_F#3_pp_rr2.flac"),
    ),
    (
        "darkgrand_F#4_f.flac",
        include_bytes!("../samples/darkgrand_F#4_f.flac"),
    ),
    (
        "darkgrand_F#4_f_rr2.flac",
        include_bytes!("../samples/darkgrand_F#4_f_rr2.flac"),
    ),
    (
        "darkgrand_F#4_mf.flac",
        include_bytes!("../samples/darkgrand_F#4_mf.flac"),
    ),
    (
        "darkgrand_F#4_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_F#4_mf_rr2.flac"),
    ),
    (
        "darkgrand_F#4_pp.flac",
        include_bytes!("../samples/darkgrand_F#4_pp.flac"),
    ),
    (
        "darkgrand_F#4_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_F#4_pp_rr2.flac"),
    ),
    (
        "darkgrand_F#5_f.flac",
        include_bytes!("../samples/darkgrand_F#5_f.flac"),
    ),
    (
        "darkgrand_F#5_f_rr2.flac",
        include_bytes!("../samples/darkgrand_F#5_f_rr2.flac"),
    ),
    (
        "darkgrand_F#5_mf.flac",
        include_bytes!("../samples/darkgrand_F#5_mf.flac"),
    ),
    (
        "darkgrand_F#5_mf_rr2.flac",
        include_bytes!("../samples/darkgrand_F#5_mf_rr2.flac"),
    ),
    (
        "darkgrand_F#5_pp.flac",
        include_bytes!("../samples/darkgrand_F#5_pp.flac"),
    ),
    (
        "darkgrand_F#5_pp_rr2.flac",
        include_bytes!("../samples/darkgrand_F#5_pp_rr2.flac"),
    ),
];

/// Returns the embedded sample bytes for an exact (case-sensitive) name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded samples; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 2208049;

    #[test]
    fn inventory_matches_packaged_samples() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| matches!(p.extension().and_then(OsStr::to_str), Some("wav" | "flac")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_bank_file_with_the_expected_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a sample");
            let riff = &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WAVE";
            let flac = &bytes[..4] == b"fLaC";
            assert!(riff || flac, "{name} is neither RIFF/WAVE nor FLAC");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
