//! Embedded first-party Yamaha B1 upright piano samples (GM 0 Acoustic Grand default, CC0=0).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through
//! `ferrosintesis`. Attribution/licence: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 52;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "b1_hard_A0.wav",
        include_bytes!("../samples/b1_hard_A0.wav"),
    ),
    (
        "b1_hard_A2.wav",
        include_bytes!("../samples/b1_hard_A2.wav"),
    ),
    (
        "b1_hard_A4.wav",
        include_bytes!("../samples/b1_hard_A4.wav"),
    ),
    (
        "b1_hard_A6.wav",
        include_bytes!("../samples/b1_hard_A6.wav"),
    ),
    (
        "b1_hard_B1.wav",
        include_bytes!("../samples/b1_hard_B1.wav"),
    ),
    (
        "b1_hard_B3.wav",
        include_bytes!("../samples/b1_hard_B3.wav"),
    ),
    (
        "b1_hard_B5.wav",
        include_bytes!("../samples/b1_hard_B5.wav"),
    ),
    (
        "b1_hard_B7.wav",
        include_bytes!("../samples/b1_hard_B7.wav"),
    ),
    (
        "b1_hard_C1.wav",
        include_bytes!("../samples/b1_hard_C1.wav"),
    ),
    (
        "b1_hard_C3.wav",
        include_bytes!("../samples/b1_hard_C3.wav"),
    ),
    (
        "b1_hard_C5.wav",
        include_bytes!("../samples/b1_hard_C5.wav"),
    ),
    (
        "b1_hard_C7.wav",
        include_bytes!("../samples/b1_hard_C7.wav"),
    ),
    (
        "b1_hard_C8.wav",
        include_bytes!("../samples/b1_hard_C8.wav"),
    ),
    (
        "b1_hard_D2.wav",
        include_bytes!("../samples/b1_hard_D2.wav"),
    ),
    (
        "b1_hard_D4.wav",
        include_bytes!("../samples/b1_hard_D4.wav"),
    ),
    (
        "b1_hard_D6.wav",
        include_bytes!("../samples/b1_hard_D6.wav"),
    ),
    (
        "b1_hard_E1.wav",
        include_bytes!("../samples/b1_hard_E1.wav"),
    ),
    (
        "b1_hard_E3.wav",
        include_bytes!("../samples/b1_hard_E3.wav"),
    ),
    (
        "b1_hard_E5.wav",
        include_bytes!("../samples/b1_hard_E5.wav"),
    ),
    (
        "b1_hard_E7.wav",
        include_bytes!("../samples/b1_hard_E7.wav"),
    ),
    (
        "b1_hard_F2.wav",
        include_bytes!("../samples/b1_hard_F2.wav"),
    ),
    (
        "b1_hard_F4.wav",
        include_bytes!("../samples/b1_hard_F4.wav"),
    ),
    (
        "b1_hard_F6.wav",
        include_bytes!("../samples/b1_hard_F6.wav"),
    ),
    (
        "b1_hard_G1.wav",
        include_bytes!("../samples/b1_hard_G1.wav"),
    ),
    (
        "b1_hard_G3.wav",
        include_bytes!("../samples/b1_hard_G3.wav"),
    ),
    (
        "b1_hard_G5.wav",
        include_bytes!("../samples/b1_hard_G5.wav"),
    ),
    (
        "b1_hard_G7.wav",
        include_bytes!("../samples/b1_hard_G7.wav"),
    ),
    (
        "b1_normal_A2.wav",
        include_bytes!("../samples/b1_normal_A2.wav"),
    ),
    (
        "b1_normal_A4.wav",
        include_bytes!("../samples/b1_normal_A4.wav"),
    ),
    (
        "b1_normal_A6.wav",
        include_bytes!("../samples/b1_normal_A6.wav"),
    ),
    (
        "b1_normal_B1.wav",
        include_bytes!("../samples/b1_normal_B1.wav"),
    ),
    (
        "b1_normal_B3.wav",
        include_bytes!("../samples/b1_normal_B3.wav"),
    ),
    (
        "b1_normal_B5.wav",
        include_bytes!("../samples/b1_normal_B5.wav"),
    ),
    (
        "b1_normal_B7.wav",
        include_bytes!("../samples/b1_normal_B7.wav"),
    ),
    (
        "b1_normal_C1.wav",
        include_bytes!("../samples/b1_normal_C1.wav"),
    ),
    (
        "b1_normal_C3.wav",
        include_bytes!("../samples/b1_normal_C3.wav"),
    ),
    (
        "b1_normal_C5.wav",
        include_bytes!("../samples/b1_normal_C5.wav"),
    ),
    (
        "b1_normal_C7.wav",
        include_bytes!("../samples/b1_normal_C7.wav"),
    ),
    (
        "b1_normal_D2.wav",
        include_bytes!("../samples/b1_normal_D2.wav"),
    ),
    (
        "b1_normal_D4.wav",
        include_bytes!("../samples/b1_normal_D4.wav"),
    ),
    (
        "b1_normal_D6.wav",
        include_bytes!("../samples/b1_normal_D6.wav"),
    ),
    (
        "b1_normal_E1.wav",
        include_bytes!("../samples/b1_normal_E1.wav"),
    ),
    (
        "b1_normal_E3.wav",
        include_bytes!("../samples/b1_normal_E3.wav"),
    ),
    (
        "b1_normal_E5.wav",
        include_bytes!("../samples/b1_normal_E5.wav"),
    ),
    (
        "b1_normal_E7.wav",
        include_bytes!("../samples/b1_normal_E7.wav"),
    ),
    (
        "b1_normal_F2.wav",
        include_bytes!("../samples/b1_normal_F2.wav"),
    ),
    (
        "b1_normal_F4.wav",
        include_bytes!("../samples/b1_normal_F4.wav"),
    ),
    (
        "b1_normal_F6.wav",
        include_bytes!("../samples/b1_normal_F6.wav"),
    ),
    (
        "b1_normal_G1.wav",
        include_bytes!("../samples/b1_normal_G1.wav"),
    ),
    (
        "b1_normal_G3.wav",
        include_bytes!("../samples/b1_normal_G3.wav"),
    ),
    (
        "b1_normal_G5.wav",
        include_bytes!("../samples/b1_normal_G5.wav"),
    ),
    (
        "b1_normal_G7.wav",
        include_bytes!("../samples/b1_normal_G7.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte sizes of the extended WAVs and their compact natural tails;
    // re-pin both only after a deterministic full-bank bake.
    const EXPECTED_BYTES: usize = 10271480;
    const EXPECTED_TAIL_BYTES: usize = 3351922;

    fn b1_tail(bytes: &[u8]) -> &[u8] {
        assert_eq!(&bytes[..4], b"RIFF");
        assert_eq!(&bytes[8..12], b"WAVE");
        let declared_end = 8 + u32::from_le_bytes(bytes[4..8].try_into().unwrap()) as usize;
        assert_eq!(declared_end, bytes.len());

        let mut pos = 12;
        let mut found = None;
        while pos < declared_end {
            assert!(pos + 8 <= declared_end);
            let len = u32::from_le_bytes(bytes[pos + 4..pos + 8].try_into().unwrap()) as usize;
            let body_start = pos + 8;
            let body_end = body_start.checked_add(len).expect("RIFF chunk overflow");
            let padded_end = body_end + (len & 1);
            assert!(padded_end <= declared_end);
            if &bytes[pos..pos + 4] == b"b1t " {
                assert!(found.is_none(), "duplicate B1 natural-tail chunk");
                assert_eq!(padded_end, declared_end, "B1 tail must be terminal");
                let body = &bytes[body_start..body_end];
                assert!(body.len() > 12, "empty B1 natural-tail payload");
                assert_eq!(body[0], 1, "unsupported B1 tail version");
                assert_eq!(body[1], 4, "unsupported B1 tail rate divisor");
                assert_eq!(&body[2..4], &[0, 0], "nonzero B1 tail reserved field");
                assert_eq!(
                    u32::from_le_bytes(body[4..8].try_into().unwrap()),
                    59_535,
                    "unexpected B1 tail entry"
                );
                let source_frames = u32::from_le_bytes(body[8..12].try_into().unwrap()) as usize;
                assert_eq!(
                    body.len() - 12,
                    source_frames.div_ceil(4),
                    "B1 tail payload length does not match its source frames"
                );
                found = Some(&body[12..]);
            }
            pos = padded_end;
        }
        found.expect("missing B1 natural-tail chunk")
    }

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_an_extended_wav_with_the_expected_aggregate_sizes() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert!(
                !b1_tail(bytes).is_empty(),
                "{name} has an empty natural tail"
            );
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(
            SAMPLES
                .iter()
                .map(|(_, bytes)| b1_tail(bytes).len())
                .sum::<usize>(),
            EXPECTED_TAIL_BYTES
        );
        assert_eq!(get("missing.wav"), None);
    }
}
