//! Embedded CC-BY 3.0 FreePats YDP (bright Yamaha Disklavier) grand samples (GM 1 Bright Acoustic alternate, CC0=1).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through
//! `ferrosintesis`. Licence/provenance: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 9;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "ydpgrand_C2.wav",
        include_bytes!("../samples/ydpgrand_C2.wav"),
    ),
    (
        "ydpgrand_C3.wav",
        include_bytes!("../samples/ydpgrand_C3.wav"),
    ),
    (
        "ydpgrand_C4.wav",
        include_bytes!("../samples/ydpgrand_C4.wav"),
    ),
    (
        "ydpgrand_C5.wav",
        include_bytes!("../samples/ydpgrand_C5.wav"),
    ),
    (
        "ydpgrand_C6.wav",
        include_bytes!("../samples/ydpgrand_C6.wav"),
    ),
    (
        "ydpgrand_F#2.wav",
        include_bytes!("../samples/ydpgrand_F#2.wav"),
    ),
    (
        "ydpgrand_F#3.wav",
        include_bytes!("../samples/ydpgrand_F#3.wav"),
    ),
    (
        "ydpgrand_F#4.wav",
        include_bytes!("../samples/ydpgrand_F#4.wav"),
    ),
    (
        "ydpgrand_F#5.wav",
        include_bytes!("../samples/ydpgrand_F#5.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 1197432;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
