//! Embedded CC0 VCSL Kawai grand-piano samples (GM 1 Bright Acoustic default).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.flac`; consumers normally reach it through `ferrosintesis`.
//! Licence/provenance: see `LICENSE-CC0` / `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of sample files embedded in this package.
pub const FILE_COUNT: usize = 32;

/// Number of exact logical names accepted, including aliases.
pub const LOGICAL_FILE_COUNT: usize = 48;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "kawai_A#3_f.flac",
        include_bytes!("../samples/kawai_A#3_f.flac"),
    ),
    (
        "kawai_A#3_mf_rr2.flac",
        include_bytes!("../samples/kawai_A#3_mf_rr2.flac"),
    ),
    (
        "kawai_A#3_pp.flac",
        include_bytes!("../samples/kawai_A#3_pp.flac"),
    ),
    (
        "kawai_A#3_pp_rr2.flac",
        include_bytes!("../samples/kawai_A#3_pp_rr2.flac"),
    ),
    (
        "kawai_A#4_f.flac",
        include_bytes!("../samples/kawai_A#4_f.flac"),
    ),
    (
        "kawai_A#4_mf_rr2.flac",
        include_bytes!("../samples/kawai_A#4_mf_rr2.flac"),
    ),
    (
        "kawai_A#4_pp.flac",
        include_bytes!("../samples/kawai_A#4_pp.flac"),
    ),
    (
        "kawai_A#4_pp_rr2.flac",
        include_bytes!("../samples/kawai_A#4_pp_rr2.flac"),
    ),
    (
        "kawai_A2_f.flac",
        include_bytes!("../samples/kawai_A2_f.flac"),
    ),
    (
        "kawai_A2_mf_rr2.flac",
        include_bytes!("../samples/kawai_A2_mf_rr2.flac"),
    ),
    (
        "kawai_A2_pp.flac",
        include_bytes!("../samples/kawai_A2_pp.flac"),
    ),
    (
        "kawai_A2_pp_rr2.flac",
        include_bytes!("../samples/kawai_A2_pp_rr2.flac"),
    ),
    (
        "kawai_C2_f.flac",
        include_bytes!("../samples/kawai_C2_f.flac"),
    ),
    (
        "kawai_C2_mf_rr2.flac",
        include_bytes!("../samples/kawai_C2_mf_rr2.flac"),
    ),
    (
        "kawai_C2_pp.flac",
        include_bytes!("../samples/kawai_C2_pp.flac"),
    ),
    (
        "kawai_C2_pp_rr2.flac",
        include_bytes!("../samples/kawai_C2_pp_rr2.flac"),
    ),
    (
        "kawai_C3_f.flac",
        include_bytes!("../samples/kawai_C3_f.flac"),
    ),
    (
        "kawai_C3_mf_rr2.flac",
        include_bytes!("../samples/kawai_C3_mf_rr2.flac"),
    ),
    (
        "kawai_C3_pp.flac",
        include_bytes!("../samples/kawai_C3_pp.flac"),
    ),
    (
        "kawai_C3_pp_rr2.flac",
        include_bytes!("../samples/kawai_C3_pp_rr2.flac"),
    ),
    (
        "kawai_C4_f.flac",
        include_bytes!("../samples/kawai_C4_f.flac"),
    ),
    (
        "kawai_C4_mf_rr2.flac",
        include_bytes!("../samples/kawai_C4_mf_rr2.flac"),
    ),
    (
        "kawai_C4_pp.flac",
        include_bytes!("../samples/kawai_C4_pp.flac"),
    ),
    (
        "kawai_C4_pp_rr2.flac",
        include_bytes!("../samples/kawai_C4_pp_rr2.flac"),
    ),
    (
        "kawai_C5_f.flac",
        include_bytes!("../samples/kawai_C5_f.flac"),
    ),
    (
        "kawai_C5_mf_rr2.flac",
        include_bytes!("../samples/kawai_C5_mf_rr2.flac"),
    ),
    (
        "kawai_C5_pp.flac",
        include_bytes!("../samples/kawai_C5_pp.flac"),
    ),
    (
        "kawai_C5_pp_rr2.flac",
        include_bytes!("../samples/kawai_C5_pp_rr2.flac"),
    ),
    (
        "kawai_C6_f.flac",
        include_bytes!("../samples/kawai_C6_f.flac"),
    ),
    (
        "kawai_C6_mf_rr2.flac",
        include_bytes!("../samples/kawai_C6_mf_rr2.flac"),
    ),
    (
        "kawai_C6_pp.flac",
        include_bytes!("../samples/kawai_C6_pp.flac"),
    ),
    (
        "kawai_C6_pp_rr2.flac",
        include_bytes!("../samples/kawai_C6_pp_rr2.flac"),
    ),
];

static ALIASES: [(&str, &str); 16] = [
    ("kawai_A#3_f_rr2.wav", "kawai_A#3_mf_rr2.flac"),
    ("kawai_A#3_mf.wav", "kawai_A#3_pp_rr2.flac"),
    ("kawai_A#4_f_rr2.wav", "kawai_A#4_mf_rr2.flac"),
    ("kawai_A#4_mf.wav", "kawai_A#4_pp_rr2.flac"),
    ("kawai_A2_f_rr2.wav", "kawai_A2_mf_rr2.flac"),
    ("kawai_A2_mf.wav", "kawai_A2_pp_rr2.flac"),
    ("kawai_C2_f_rr2.wav", "kawai_C2_mf_rr2.flac"),
    ("kawai_C2_mf.wav", "kawai_C2_pp_rr2.flac"),
    ("kawai_C3_f_rr2.wav", "kawai_C3_mf_rr2.flac"),
    ("kawai_C3_mf.wav", "kawai_C3_pp_rr2.flac"),
    ("kawai_C4_f_rr2.wav", "kawai_C4_mf_rr2.flac"),
    ("kawai_C4_mf.wav", "kawai_C4_pp_rr2.flac"),
    ("kawai_C5_f_rr2.wav", "kawai_C5_mf_rr2.flac"),
    ("kawai_C5_mf.wav", "kawai_C5_pp_rr2.flac"),
    ("kawai_C6_f_rr2.wav", "kawai_C6_mf_rr2.flac"),
    ("kawai_C6_mf.wav", "kawai_C6_pp_rr2.flac"),
];

/// Returns the embedded sample bytes for an exact (case-sensitive) name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    let name = ALIASES
        .iter()
        .find(|(alias, _)| *alias == name)
        .map_or(name, |(_, canonical)| *canonical);
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded samples; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 1733440;

    #[test]
    fn inventory_matches_packaged_samples() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| matches!(p.extension().and_then(OsStr::to_str), Some("wav" | "flac")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_bank_file_with_the_expected_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a sample");
            let riff = &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WAVE";
            let flac = &bytes[..4] == b"fLaC";
            assert!(riff || flac, "{name} is neither RIFF/WAVE nor FLAC");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }

    #[test]
    fn aliases_resolve_without_duplicate_physical_payloads() {
        assert_eq!(LOGICAL_FILE_COUNT, FILE_COUNT + ALIASES.len());
        let declared: Vec<(&str, &str)> = include_str!("../ALIASES")
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                if line.is_empty() || line.starts_with('#') {
                    return None;
                }
                let mut fields = line.split_whitespace();
                let pair = (fields.next().unwrap(), fields.next().unwrap());
                assert!(fields.next().is_none(), "malformed alias row {line}");
                Some(pair)
            })
            .collect();
        assert_eq!(declared, ALIASES);
        for (alias, canonical) in ALIASES {
            let bytes = get(canonical).unwrap_or_else(|| {
                panic!("alias {alias} names {canonical}, which is not packaged")
            });
            assert!(!bytes.is_empty(), "alias {alias} resolves to empty bytes");
            assert_eq!(get(alias), Some(bytes), "alias {alias}");
        }
        for (left, (left_name, left_bytes)) in SAMPLES.iter().copied().enumerate() {
            for (right_name, right_bytes) in SAMPLES.iter().copied().skip(left + 1) {
                assert!(
                    left_bytes != right_bytes,
                    "undeclared duplicate payloads: {} and {}",
                    left_name,
                    right_name
                );
            }
        }
    }
}
