//! Embedded CC0 VCSL Kawai grand-piano samples (GM 1 Bright Acoustic default).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through
//! `ferrosintesis`. Attribution/licence: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 48;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "kawai_A#3_f.wav",
        include_bytes!("../samples/kawai_A#3_f.wav"),
    ),
    (
        "kawai_A#3_f_rr2.wav",
        include_bytes!("../samples/kawai_A#3_f_rr2.wav"),
    ),
    (
        "kawai_A#3_mf.wav",
        include_bytes!("../samples/kawai_A#3_mf.wav"),
    ),
    (
        "kawai_A#3_mf_rr2.wav",
        include_bytes!("../samples/kawai_A#3_mf_rr2.wav"),
    ),
    (
        "kawai_A#3_pp.wav",
        include_bytes!("../samples/kawai_A#3_pp.wav"),
    ),
    (
        "kawai_A#3_pp_rr2.wav",
        include_bytes!("../samples/kawai_A#3_pp_rr2.wav"),
    ),
    (
        "kawai_A#4_f.wav",
        include_bytes!("../samples/kawai_A#4_f.wav"),
    ),
    (
        "kawai_A#4_f_rr2.wav",
        include_bytes!("../samples/kawai_A#4_f_rr2.wav"),
    ),
    (
        "kawai_A#4_mf.wav",
        include_bytes!("../samples/kawai_A#4_mf.wav"),
    ),
    (
        "kawai_A#4_mf_rr2.wav",
        include_bytes!("../samples/kawai_A#4_mf_rr2.wav"),
    ),
    (
        "kawai_A#4_pp.wav",
        include_bytes!("../samples/kawai_A#4_pp.wav"),
    ),
    (
        "kawai_A#4_pp_rr2.wav",
        include_bytes!("../samples/kawai_A#4_pp_rr2.wav"),
    ),
    (
        "kawai_A2_f.wav",
        include_bytes!("../samples/kawai_A2_f.wav"),
    ),
    (
        "kawai_A2_f_rr2.wav",
        include_bytes!("../samples/kawai_A2_f_rr2.wav"),
    ),
    (
        "kawai_A2_mf.wav",
        include_bytes!("../samples/kawai_A2_mf.wav"),
    ),
    (
        "kawai_A2_mf_rr2.wav",
        include_bytes!("../samples/kawai_A2_mf_rr2.wav"),
    ),
    (
        "kawai_A2_pp.wav",
        include_bytes!("../samples/kawai_A2_pp.wav"),
    ),
    (
        "kawai_A2_pp_rr2.wav",
        include_bytes!("../samples/kawai_A2_pp_rr2.wav"),
    ),
    (
        "kawai_C2_f.wav",
        include_bytes!("../samples/kawai_C2_f.wav"),
    ),
    (
        "kawai_C2_f_rr2.wav",
        include_bytes!("../samples/kawai_C2_f_rr2.wav"),
    ),
    (
        "kawai_C2_mf.wav",
        include_bytes!("../samples/kawai_C2_mf.wav"),
    ),
    (
        "kawai_C2_mf_rr2.wav",
        include_bytes!("../samples/kawai_C2_mf_rr2.wav"),
    ),
    (
        "kawai_C2_pp.wav",
        include_bytes!("../samples/kawai_C2_pp.wav"),
    ),
    (
        "kawai_C2_pp_rr2.wav",
        include_bytes!("../samples/kawai_C2_pp_rr2.wav"),
    ),
    (
        "kawai_C3_f.wav",
        include_bytes!("../samples/kawai_C3_f.wav"),
    ),
    (
        "kawai_C3_f_rr2.wav",
        include_bytes!("../samples/kawai_C3_f_rr2.wav"),
    ),
    (
        "kawai_C3_mf.wav",
        include_bytes!("../samples/kawai_C3_mf.wav"),
    ),
    (
        "kawai_C3_mf_rr2.wav",
        include_bytes!("../samples/kawai_C3_mf_rr2.wav"),
    ),
    (
        "kawai_C3_pp.wav",
        include_bytes!("../samples/kawai_C3_pp.wav"),
    ),
    (
        "kawai_C3_pp_rr2.wav",
        include_bytes!("../samples/kawai_C3_pp_rr2.wav"),
    ),
    (
        "kawai_C4_f.wav",
        include_bytes!("../samples/kawai_C4_f.wav"),
    ),
    (
        "kawai_C4_f_rr2.wav",
        include_bytes!("../samples/kawai_C4_f_rr2.wav"),
    ),
    (
        "kawai_C4_mf.wav",
        include_bytes!("../samples/kawai_C4_mf.wav"),
    ),
    (
        "kawai_C4_mf_rr2.wav",
        include_bytes!("../samples/kawai_C4_mf_rr2.wav"),
    ),
    (
        "kawai_C4_pp.wav",
        include_bytes!("../samples/kawai_C4_pp.wav"),
    ),
    (
        "kawai_C4_pp_rr2.wav",
        include_bytes!("../samples/kawai_C4_pp_rr2.wav"),
    ),
    (
        "kawai_C5_f.wav",
        include_bytes!("../samples/kawai_C5_f.wav"),
    ),
    (
        "kawai_C5_f_rr2.wav",
        include_bytes!("../samples/kawai_C5_f_rr2.wav"),
    ),
    (
        "kawai_C5_mf.wav",
        include_bytes!("../samples/kawai_C5_mf.wav"),
    ),
    (
        "kawai_C5_mf_rr2.wav",
        include_bytes!("../samples/kawai_C5_mf_rr2.wav"),
    ),
    (
        "kawai_C5_pp.wav",
        include_bytes!("../samples/kawai_C5_pp.wav"),
    ),
    (
        "kawai_C5_pp_rr2.wav",
        include_bytes!("../samples/kawai_C5_pp_rr2.wav"),
    ),
    (
        "kawai_C6_f.wav",
        include_bytes!("../samples/kawai_C6_f.wav"),
    ),
    (
        "kawai_C6_f_rr2.wav",
        include_bytes!("../samples/kawai_C6_f_rr2.wav"),
    ),
    (
        "kawai_C6_mf.wav",
        include_bytes!("../samples/kawai_C6_mf.wav"),
    ),
    (
        "kawai_C6_mf_rr2.wav",
        include_bytes!("../samples/kawai_C6_mf_rr2.wav"),
    ),
    (
        "kawai_C6_pp.wav",
        include_bytes!("../samples/kawai_C6_pp.wav"),
    ),
    (
        "kawai_C6_pp_rr2.wav",
        include_bytes!("../samples/kawai_C6_pp_rr2.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 6386304;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
