//! Embedded CC0 FreePats electric-bass (Yamaha RBX) onset samples: GM 33 finger, GM 34 pick, GM 35 fretless (rides finger).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through
//! `ferrosintesis`. Licence/provenance: see `LICENSE-CC0` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 13;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "fingerbass_A#1.wav",
        include_bytes!("../samples/fingerbass_A#1.wav"),
    ),
    (
        "fingerbass_C2.wav",
        include_bytes!("../samples/fingerbass_C2.wav"),
    ),
    (
        "fingerbass_D2.wav",
        include_bytes!("../samples/fingerbass_D2.wav"),
    ),
    (
        "fingerbass_E1.wav",
        include_bytes!("../samples/fingerbass_E1.wav"),
    ),
    (
        "fingerbass_F#1.wav",
        include_bytes!("../samples/fingerbass_F#1.wav"),
    ),
    (
        "fingerbass_G#1.wav",
        include_bytes!("../samples/fingerbass_G#1.wav"),
    ),
    (
        "pickbass_A#1.wav",
        include_bytes!("../samples/pickbass_A#1.wav"),
    ),
    (
        "pickbass_C2.wav",
        include_bytes!("../samples/pickbass_C2.wav"),
    ),
    (
        "pickbass_D2.wav",
        include_bytes!("../samples/pickbass_D2.wav"),
    ),
    (
        "pickbass_E1.wav",
        include_bytes!("../samples/pickbass_E1.wav"),
    ),
    (
        "pickbass_E2.wav",
        include_bytes!("../samples/pickbass_E2.wav"),
    ),
    (
        "pickbass_F#1.wav",
        include_bytes!("../samples/pickbass_F#1.wav"),
    ),
    (
        "pickbass_G#1.wav",
        include_bytes!("../samples/pickbass_G#1.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 1041664;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
