//! Embedded CC0 attack-transient samples for orchestral and drum voices.
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through
//! `ferrosintesis`. Attribution/licence: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 166;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "bassoon_A#0_f.wav",
        include_bytes!("../samples/bassoon_A#0_f.wav"),
    ),
    (
        "bassoon_A#0_p.wav",
        include_bytes!("../samples/bassoon_A#0_p.wav"),
    ),
    (
        "bassoon_C2_f.wav",
        include_bytes!("../samples/bassoon_C2_f.wav"),
    ),
    (
        "bassoon_C2_p.wav",
        include_bytes!("../samples/bassoon_C2_p.wav"),
    ),
    (
        "bassoon_C4_f.wav",
        include_bytes!("../samples/bassoon_C4_f.wav"),
    ),
    (
        "bassoon_C4_p.wav",
        include_bytes!("../samples/bassoon_C4_p.wav"),
    ),
    (
        "bassoon_D#3_f.wav",
        include_bytes!("../samples/bassoon_D#3_f.wav"),
    ),
    (
        "bassoon_D#3_p.wav",
        include_bytes!("../samples/bassoon_D#3_p.wav"),
    ),
    (
        "bassoon_F1_f.wav",
        include_bytes!("../samples/bassoon_F1_f.wav"),
    ),
    (
        "bassoon_F1_p.wav",
        include_bytes!("../samples/bassoon_F1_p.wav"),
    ),
    (
        "bassoon_G2_f.wav",
        include_bytes!("../samples/bassoon_G2_f.wav"),
    ),
    (
        "bassoon_G2_p.wav",
        include_bytes!("../samples/bassoon_G2_p.wav"),
    ),
    (
        "celens_A2_f.wav",
        include_bytes!("../samples/celens_A2_f.wav"),
    ),
    (
        "celens_A2_p.wav",
        include_bytes!("../samples/celens_A2_p.wav"),
    ),
    (
        "celens_B3_f.wav",
        include_bytes!("../samples/celens_B3_f.wav"),
    ),
    (
        "celens_B3_p.wav",
        include_bytes!("../samples/celens_B3_p.wav"),
    ),
    (
        "celens_C1_f.wav",
        include_bytes!("../samples/celens_C1_f.wav"),
    ),
    (
        "celens_C1_p.wav",
        include_bytes!("../samples/celens_C1_p.wav"),
    ),
    (
        "celens_D2_f.wav",
        include_bytes!("../samples/celens_D2_f.wav"),
    ),
    (
        "celens_D2_p.wav",
        include_bytes!("../samples/celens_D2_p.wav"),
    ),
    (
        "celens_E3_f.wav",
        include_bytes!("../samples/celens_E3_f.wav"),
    ),
    (
        "celens_E3_p.wav",
        include_bytes!("../samples/celens_E3_p.wav"),
    ),
    (
        "celens_G1_f.wav",
        include_bytes!("../samples/celens_G1_f.wav"),
    ),
    (
        "celens_G1_p.wav",
        include_bytes!("../samples/celens_G1_p.wav"),
    ),
    (
        "chanter_A#4.wav",
        include_bytes!("../samples/chanter_A#4.wav"),
    ),
    (
        "chanter_A#4_rr2.wav",
        include_bytes!("../samples/chanter_A#4_rr2.wav"),
    ),
    (
        "chanter_A4.wav",
        include_bytes!("../samples/chanter_A4.wav"),
    ),
    (
        "chanter_A4_rr2.wav",
        include_bytes!("../samples/chanter_A4_rr2.wav"),
    ),
    (
        "chanter_B4.wav",
        include_bytes!("../samples/chanter_B4.wav"),
    ),
    (
        "chanter_B4_rr2.wav",
        include_bytes!("../samples/chanter_B4_rr2.wav"),
    ),
    (
        "chanter_C#5.wav",
        include_bytes!("../samples/chanter_C#5.wav"),
    ),
    (
        "chanter_C5.wav",
        include_bytes!("../samples/chanter_C5.wav"),
    ),
    (
        "chanter_C5_rr2.wav",
        include_bytes!("../samples/chanter_C5_rr2.wav"),
    ),
    (
        "chanter_D5.wav",
        include_bytes!("../samples/chanter_D5.wav"),
    ),
    (
        "chanter_D5_rr2.wav",
        include_bytes!("../samples/chanter_D5_rr2.wav"),
    ),
    (
        "chanter_F#5.wav",
        include_bytes!("../samples/chanter_F#5.wav"),
    ),
    (
        "chanter_F4.wav",
        include_bytes!("../samples/chanter_F4.wav"),
    ),
    (
        "chanter_G4.wav",
        include_bytes!("../samples/chanter_G4.wav"),
    ),
    (
        "chanter_G5.wav",
        include_bytes!("../samples/chanter_G5.wav"),
    ),
    (
        "clarinet_A#2_f.wav",
        include_bytes!("../samples/clarinet_A#2_f.wav"),
    ),
    (
        "clarinet_A#2_p.wav",
        include_bytes!("../samples/clarinet_A#2_p.wav"),
    ),
    (
        "clarinet_A#3_f.wav",
        include_bytes!("../samples/clarinet_A#3_f.wav"),
    ),
    (
        "clarinet_A#3_p.wav",
        include_bytes!("../samples/clarinet_A#3_p.wav"),
    ),
    (
        "clarinet_D3_f.wav",
        include_bytes!("../samples/clarinet_D3_f.wav"),
    ),
    (
        "clarinet_D3_p.wav",
        include_bytes!("../samples/clarinet_D3_p.wav"),
    ),
    (
        "clarinet_D4_f.wav",
        include_bytes!("../samples/clarinet_D4_f.wav"),
    ),
    (
        "clarinet_D4_p.wav",
        include_bytes!("../samples/clarinet_D4_p.wav"),
    ),
    (
        "clarinet_F3_f.wav",
        include_bytes!("../samples/clarinet_F3_f.wav"),
    ),
    (
        "clarinet_F3_p.wav",
        include_bytes!("../samples/clarinet_F3_p.wav"),
    ),
    (
        "clarinet_F4_f.wav",
        include_bytes!("../samples/clarinet_F4_f.wav"),
    ),
    (
        "clarinet_F4_p.wav",
        include_bytes!("../samples/clarinet_F4_p.wav"),
    ),
    ("drone_G2.wav", include_bytes!("../samples/drone_G2.wav")),
    ("drone_G3.wav", include_bytes!("../samples/drone_G3.wav")),
    (
        "drum_crash1_ff_rr1.wav",
        include_bytes!("../samples/drum_crash1_ff_rr1.wav"),
    ),
    (
        "drum_crash1_ff_rr2.wav",
        include_bytes!("../samples/drum_crash1_ff_rr2.wav"),
    ),
    (
        "drum_kick_v3_rr1.wav",
        include_bytes!("../samples/drum_kick_v3_rr1.wav"),
    ),
    (
        "drum_kick_v3_rr2.wav",
        include_bytes!("../samples/drum_kick_v3_rr2.wav"),
    ),
    (
        "drum_snare2_v5_rr1.wav",
        include_bytes!("../samples/drum_snare2_v5_rr1.wav"),
    ),
    (
        "drum_snare2_v5_rr2.wav",
        include_bytes!("../samples/drum_snare2_v5_rr2.wav"),
    ),
    (
        "drum_sus_cymb1_mp_rr1.wav",
        include_bytes!("../samples/drum_sus_cymb1_mp_rr1.wav"),
    ),
    (
        "drum_sus_cymb1_mp_rr2.wav",
        include_bytes!("../samples/drum_sus_cymb1_mp_rr2.wav"),
    ),
    ("harpsi_C2.wav", include_bytes!("../samples/harpsi_C2.wav")),
    ("harpsi_C3.wav", include_bytes!("../samples/harpsi_C3.wav")),
    ("harpsi_C4.wav", include_bytes!("../samples/harpsi_C4.wav")),
    ("harpsi_C5.wav", include_bytes!("../samples/harpsi_C5.wav")),
    ("harpsi_C6.wav", include_bytes!("../samples/harpsi_C6.wav")),
    ("harpsi_F2.wav", include_bytes!("../samples/harpsi_F2.wav")),
    ("harpsi_F3.wav", include_bytes!("../samples/harpsi_F3.wav")),
    ("harpsi_F4.wav", include_bytes!("../samples/harpsi_F4.wav")),
    ("harpsi_F5.wav", include_bytes!("../samples/harpsi_F5.wav")),
    ("harpsi_F6.wav", include_bytes!("../samples/harpsi_F6.wav")),
    (
        "horn_A#1_f.wav",
        include_bytes!("../samples/horn_A#1_f.wav"),
    ),
    (
        "horn_A#1_p.wav",
        include_bytes!("../samples/horn_A#1_p.wav"),
    ),
    ("horn_A2_f.wav", include_bytes!("../samples/horn_A2_f.wav")),
    ("horn_A2_p.wav", include_bytes!("../samples/horn_A2_p.wav")),
    ("horn_C3_f.wav", include_bytes!("../samples/horn_C3_f.wav")),
    ("horn_C3_p.wav", include_bytes!("../samples/horn_C3_p.wav")),
    ("horn_D2_f.wav", include_bytes!("../samples/horn_D2_f.wav")),
    ("horn_D2_p.wav", include_bytes!("../samples/horn_D2_p.wav")),
    ("horn_D4_f.wav", include_bytes!("../samples/horn_D4_f.wav")),
    ("horn_D4_p.wav", include_bytes!("../samples/horn_D4_p.wav")),
    ("horn_F2_f.wav", include_bytes!("../samples/horn_F2_f.wav")),
    ("horn_F2_p.wav", include_bytes!("../samples/horn_F2_p.wav")),
    (
        "mutetpt_A#2_f.wav",
        include_bytes!("../samples/mutetpt_A#2_f.wav"),
    ),
    (
        "mutetpt_A#2_p.wav",
        include_bytes!("../samples/mutetpt_A#2_p.wav"),
    ),
    (
        "mutetpt_A4_f.wav",
        include_bytes!("../samples/mutetpt_A4_f.wav"),
    ),
    (
        "mutetpt_A4_p.wav",
        include_bytes!("../samples/mutetpt_A4_p.wav"),
    ),
    (
        "mutetpt_D3_f.wav",
        include_bytes!("../samples/mutetpt_D3_f.wav"),
    ),
    (
        "mutetpt_D3_p.wav",
        include_bytes!("../samples/mutetpt_D3_p.wav"),
    ),
    (
        "mutetpt_D4_f.wav",
        include_bytes!("../samples/mutetpt_D4_f.wav"),
    ),
    (
        "mutetpt_D4_p.wav",
        include_bytes!("../samples/mutetpt_D4_p.wav"),
    ),
    (
        "mutetpt_G3_f.wav",
        include_bytes!("../samples/mutetpt_G3_f.wav"),
    ),
    (
        "mutetpt_G3_p.wav",
        include_bytes!("../samples/mutetpt_G3_p.wav"),
    ),
    ("nylon_A#3.wav", include_bytes!("../samples/nylon_A#3.wav")),
    ("nylon_A#4.wav", include_bytes!("../samples/nylon_A#4.wav")),
    ("nylon_B2.wav", include_bytes!("../samples/nylon_B2.wav")),
    ("nylon_E2.wav", include_bytes!("../samples/nylon_E2.wav")),
    ("nylon_E3.wav", include_bytes!("../samples/nylon_E3.wav")),
    ("nylon_E4.wav", include_bytes!("../samples/nylon_E4.wav")),
    ("nylon_E5.wav", include_bytes!("../samples/nylon_E5.wav")),
    (
        "oboe_A#3_f.wav",
        include_bytes!("../samples/oboe_A#3_f.wav"),
    ),
    (
        "oboe_A#3_p.wav",
        include_bytes!("../samples/oboe_A#3_p.wav"),
    ),
    (
        "oboe_A#4_f.wav",
        include_bytes!("../samples/oboe_A#4_f.wav"),
    ),
    (
        "oboe_A#4_p.wav",
        include_bytes!("../samples/oboe_A#4_p.wav"),
    ),
    ("oboe_D3_f.wav", include_bytes!("../samples/oboe_D3_f.wav")),
    ("oboe_D3_p.wav", include_bytes!("../samples/oboe_D3_p.wav")),
    ("oboe_D4_f.wav", include_bytes!("../samples/oboe_D4_f.wav")),
    ("oboe_D4_p.wav", include_bytes!("../samples/oboe_D4_p.wav")),
    ("oboe_F3_f.wav", include_bytes!("../samples/oboe_F3_f.wav")),
    ("oboe_F3_p.wav", include_bytes!("../samples/oboe_F3_p.wav")),
    ("oboe_F4_f.wav", include_bytes!("../samples/oboe_F4_f.wav")),
    ("oboe_F4_p.wav", include_bytes!("../samples/oboe_F4_p.wav")),
    ("steel_A#2.wav", include_bytes!("../samples/steel_A#2.wav")),
    ("steel_A#3.wav", include_bytes!("../samples/steel_A#3.wav")),
    ("steel_B4.wav", include_bytes!("../samples/steel_B4.wav")),
    ("steel_B5.wav", include_bytes!("../samples/steel_B5.wav")),
    ("steel_E2.wav", include_bytes!("../samples/steel_E2.wav")),
    ("steel_E3.wav", include_bytes!("../samples/steel_E3.wav")),
    ("steel_E4.wav", include_bytes!("../samples/steel_E4.wav")),
    ("steel_F5.wav", include_bytes!("../samples/steel_F5.wav")),
    (
        "trombone_A#1_f.wav",
        include_bytes!("../samples/trombone_A#1_f.wav"),
    ),
    (
        "trombone_A#1_p.wav",
        include_bytes!("../samples/trombone_A#1_p.wav"),
    ),
    (
        "trombone_C3_f.wav",
        include_bytes!("../samples/trombone_C3_f.wav"),
    ),
    (
        "trombone_C3_p.wav",
        include_bytes!("../samples/trombone_C3_p.wav"),
    ),
    (
        "trombone_D2_f.wav",
        include_bytes!("../samples/trombone_D2_f.wav"),
    ),
    (
        "trombone_D2_p.wav",
        include_bytes!("../samples/trombone_D2_p.wav"),
    ),
    (
        "trombone_F1_f.wav",
        include_bytes!("../samples/trombone_F1_f.wav"),
    ),
    (
        "trombone_F1_p.wav",
        include_bytes!("../samples/trombone_F1_p.wav"),
    ),
    (
        "trombone_F2_f.wav",
        include_bytes!("../samples/trombone_F2_f.wav"),
    ),
    (
        "trombone_F2_p.wav",
        include_bytes!("../samples/trombone_F2_p.wav"),
    ),
    (
        "trombone_F3_f.wav",
        include_bytes!("../samples/trombone_F3_f.wav"),
    ),
    (
        "trombone_F3_p.wav",
        include_bytes!("../samples/trombone_F3_p.wav"),
    ),
    (
        "trumpet_A4_f.wav",
        include_bytes!("../samples/trumpet_A4_f.wav"),
    ),
    (
        "trumpet_A4_p.wav",
        include_bytes!("../samples/trumpet_A4_p.wav"),
    ),
    (
        "trumpet_C3_f.wav",
        include_bytes!("../samples/trumpet_C3_f.wav"),
    ),
    (
        "trumpet_C3_p.wav",
        include_bytes!("../samples/trumpet_C3_p.wav"),
    ),
    (
        "trumpet_D4_f.wav",
        include_bytes!("../samples/trumpet_D4_f.wav"),
    ),
    (
        "trumpet_D4_p.wav",
        include_bytes!("../samples/trumpet_D4_p.wav"),
    ),
    (
        "trumpet_F2_f.wav",
        include_bytes!("../samples/trumpet_F2_f.wav"),
    ),
    (
        "trumpet_F2_p.wav",
        include_bytes!("../samples/trumpet_F2_p.wav"),
    ),
    (
        "trumpet_G3_f.wav",
        include_bytes!("../samples/trumpet_G3_f.wav"),
    ),
    (
        "trumpet_G3_p.wav",
        include_bytes!("../samples/trumpet_G3_p.wav"),
    ),
    (
        "tuba_A#0_f.wav",
        include_bytes!("../samples/tuba_A#0_f.wav"),
    ),
    (
        "tuba_A#0_p.wav",
        include_bytes!("../samples/tuba_A#0_p.wav"),
    ),
    (
        "tuba_A#1_f.wav",
        include_bytes!("../samples/tuba_A#1_f.wav"),
    ),
    (
        "tuba_A#1_p.wav",
        include_bytes!("../samples/tuba_A#1_p.wav"),
    ),
    (
        "tuba_A#2_f.wav",
        include_bytes!("../samples/tuba_A#2_f.wav"),
    ),
    (
        "tuba_A#2_p.wav",
        include_bytes!("../samples/tuba_A#2_p.wav"),
    ),
    (
        "tuba_D#1_f.wav",
        include_bytes!("../samples/tuba_D#1_f.wav"),
    ),
    (
        "tuba_D#1_p.wav",
        include_bytes!("../samples/tuba_D#1_p.wav"),
    ),
    ("tuba_D2_f.wav", include_bytes!("../samples/tuba_D2_f.wav")),
    ("tuba_D2_p.wav", include_bytes!("../samples/tuba_D2_p.wav")),
    ("tuba_F2_f.wav", include_bytes!("../samples/tuba_F2_f.wav")),
    ("tuba_F2_p.wav", include_bytes!("../samples/tuba_F2_p.wav")),
    (
        "vlnens_A3_f.wav",
        include_bytes!("../samples/vlnens_A3_f.wav"),
    ),
    (
        "vlnens_A3_p.wav",
        include_bytes!("../samples/vlnens_A3_p.wav"),
    ),
    (
        "vlnens_B4_f.wav",
        include_bytes!("../samples/vlnens_B4_f.wav"),
    ),
    (
        "vlnens_B4_p.wav",
        include_bytes!("../samples/vlnens_B4_p.wav"),
    ),
    (
        "vlnens_D3_f.wav",
        include_bytes!("../samples/vlnens_D3_f.wav"),
    ),
    (
        "vlnens_D3_p.wav",
        include_bytes!("../samples/vlnens_D3_p.wav"),
    ),
    (
        "vlnens_D5_f.wav",
        include_bytes!("../samples/vlnens_D5_f.wav"),
    ),
    (
        "vlnens_D5_p.wav",
        include_bytes!("../samples/vlnens_D5_p.wav"),
    ),
    (
        "vlnens_E4_f.wav",
        include_bytes!("../samples/vlnens_E4_f.wav"),
    ),
    (
        "vlnens_E4_p.wav",
        include_bytes!("../samples/vlnens_E4_p.wav"),
    ),
    (
        "vlnens_G2_f.wav",
        include_bytes!("../samples/vlnens_G2_f.wav"),
    ),
    (
        "vlnens_G2_p.wav",
        include_bytes!("../samples/vlnens_G2_p.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 9471294;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
