//! Embedded CC0 VCSL Steinway-B grand-piano samples (GM 0 acoustic-grand alternate, CC0=3).
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through
//! `ferrosintesis`. Licence/provenance: see `LICENSE-CC0` / `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 27;

/// Number of exact logical names accepted, including aliases.
pub const LOGICAL_FILE_COUNT: usize = 54;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "steinwayb_C2_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_C2_mf_rr2.wav"),
    ),
    (
        "steinwayb_C2_pp.wav",
        include_bytes!("../samples/steinwayb_C2_pp.wav"),
    ),
    (
        "steinwayb_C2_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_C2_pp_rr2.wav"),
    ),
    (
        "steinwayb_C3_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_C3_mf_rr2.wav"),
    ),
    (
        "steinwayb_C3_pp.wav",
        include_bytes!("../samples/steinwayb_C3_pp.wav"),
    ),
    (
        "steinwayb_C3_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_C3_pp_rr2.wav"),
    ),
    (
        "steinwayb_C4_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_C4_mf_rr2.wav"),
    ),
    (
        "steinwayb_C4_pp.wav",
        include_bytes!("../samples/steinwayb_C4_pp.wav"),
    ),
    (
        "steinwayb_C4_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_C4_pp_rr2.wav"),
    ),
    (
        "steinwayb_C5_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_C5_mf_rr2.wav"),
    ),
    (
        "steinwayb_C5_pp.wav",
        include_bytes!("../samples/steinwayb_C5_pp.wav"),
    ),
    (
        "steinwayb_C5_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_C5_pp_rr2.wav"),
    ),
    (
        "steinwayb_C6_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_C6_mf_rr2.wav"),
    ),
    (
        "steinwayb_C6_pp.wav",
        include_bytes!("../samples/steinwayb_C6_pp.wav"),
    ),
    (
        "steinwayb_C6_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_C6_pp_rr2.wav"),
    ),
    (
        "steinwayb_F#2_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_F#2_mf_rr2.wav"),
    ),
    (
        "steinwayb_F#2_pp.wav",
        include_bytes!("../samples/steinwayb_F#2_pp.wav"),
    ),
    (
        "steinwayb_F#2_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_F#2_pp_rr2.wav"),
    ),
    (
        "steinwayb_F#3_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_F#3_mf_rr2.wav"),
    ),
    (
        "steinwayb_F#3_pp.wav",
        include_bytes!("../samples/steinwayb_F#3_pp.wav"),
    ),
    (
        "steinwayb_F#3_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_F#3_pp_rr2.wav"),
    ),
    (
        "steinwayb_F#4_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_F#4_mf_rr2.wav"),
    ),
    (
        "steinwayb_F#4_pp.wav",
        include_bytes!("../samples/steinwayb_F#4_pp.wav"),
    ),
    (
        "steinwayb_F#4_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_F#4_pp_rr2.wav"),
    ),
    (
        "steinwayb_F#5_mf_rr2.wav",
        include_bytes!("../samples/steinwayb_F#5_mf_rr2.wav"),
    ),
    (
        "steinwayb_F#5_pp.wav",
        include_bytes!("../samples/steinwayb_F#5_pp.wav"),
    ),
    (
        "steinwayb_F#5_pp_rr2.wav",
        include_bytes!("../samples/steinwayb_F#5_pp_rr2.wav"),
    ),
];

static ALIASES: [(&str, &str); 27] = [
    ("steinwayb_C2_f.wav", "steinwayb_C2_mf_rr2.wav"),
    ("steinwayb_C2_f_rr2.wav", "steinwayb_C2_pp_rr2.wav"),
    ("steinwayb_C2_mf.wav", "steinwayb_C2_pp_rr2.wav"),
    ("steinwayb_C3_f.wav", "steinwayb_C3_mf_rr2.wav"),
    ("steinwayb_C3_f_rr2.wav", "steinwayb_C3_pp_rr2.wav"),
    ("steinwayb_C3_mf.wav", "steinwayb_C3_pp_rr2.wav"),
    ("steinwayb_C4_f.wav", "steinwayb_C4_mf_rr2.wav"),
    ("steinwayb_C4_f_rr2.wav", "steinwayb_C4_pp_rr2.wav"),
    ("steinwayb_C4_mf.wav", "steinwayb_C4_pp_rr2.wav"),
    ("steinwayb_C5_f.wav", "steinwayb_C5_mf_rr2.wav"),
    ("steinwayb_C5_f_rr2.wav", "steinwayb_C5_pp_rr2.wav"),
    ("steinwayb_C5_mf.wav", "steinwayb_C5_pp_rr2.wav"),
    ("steinwayb_C6_f.wav", "steinwayb_C6_mf_rr2.wav"),
    ("steinwayb_C6_f_rr2.wav", "steinwayb_C6_pp_rr2.wav"),
    ("steinwayb_C6_mf.wav", "steinwayb_C6_pp_rr2.wav"),
    ("steinwayb_F#2_f.wav", "steinwayb_F#2_mf_rr2.wav"),
    ("steinwayb_F#2_f_rr2.wav", "steinwayb_F#2_pp_rr2.wav"),
    ("steinwayb_F#2_mf.wav", "steinwayb_F#2_pp_rr2.wav"),
    ("steinwayb_F#3_f.wav", "steinwayb_F#3_mf_rr2.wav"),
    ("steinwayb_F#3_f_rr2.wav", "steinwayb_F#3_pp_rr2.wav"),
    ("steinwayb_F#3_mf.wav", "steinwayb_F#3_pp_rr2.wav"),
    ("steinwayb_F#4_f.wav", "steinwayb_F#4_mf_rr2.wav"),
    ("steinwayb_F#4_f_rr2.wav", "steinwayb_F#4_pp_rr2.wav"),
    ("steinwayb_F#4_mf.wav", "steinwayb_F#4_pp_rr2.wav"),
    ("steinwayb_F#5_f.wav", "steinwayb_F#5_mf_rr2.wav"),
    ("steinwayb_F#5_f_rr2.wav", "steinwayb_F#5_pp_rr2.wav"),
    ("steinwayb_F#5_mf.wav", "steinwayb_F#5_pp_rr2.wav"),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    let name = ALIASES
        .iter()
        .find(|(alias, _)| *alias == name)
        .map_or(name, |(_, canonical)| *canonical);
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 3592296;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }

    #[test]
    fn aliases_resolve_without_duplicate_physical_payloads() {
        assert_eq!(LOGICAL_FILE_COUNT, FILE_COUNT + ALIASES.len());
        let declared: Vec<(&str, &str)> = include_str!("../ALIASES")
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                if line.is_empty() || line.starts_with('#') {
                    return None;
                }
                let mut fields = line.split_whitespace();
                let pair = (fields.next().unwrap(), fields.next().unwrap());
                assert!(fields.next().is_none(), "malformed alias row {line}");
                Some(pair)
            })
            .collect();
        assert_eq!(declared, ALIASES);
        for (alias, canonical) in ALIASES {
            assert_eq!(get(alias), get(canonical), "alias {alias}");
        }
        for (left, (left_name, left_bytes)) in SAMPLES.iter().copied().enumerate() {
            for (right_name, right_bytes) in SAMPLES.iter().copied().skip(left + 1) {
                assert!(
                    left_bytes != right_bytes,
                    "undeclared duplicate payloads: {} and {}",
                    left_name,
                    right_name
                );
            }
        }
    }
}
