//! Embedded CC-BY Freesound onset samples: GM 4 Rhodes (tim.kahn) + GM 15 hammered dulcimer (iternetcone). Attribution: see NOTICE.
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.flac`; consumers normally reach it through `ferrosintesis`.
//! Licence/provenance: see `NOTICE` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of sample files embedded in this package.
pub const FILE_COUNT: usize = 20;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "dulcimer_A4.flac",
        include_bytes!("../samples/dulcimer_A4.flac"),
    ),
    (
        "dulcimer_B4.flac",
        include_bytes!("../samples/dulcimer_B4.flac"),
    ),
    (
        "dulcimer_C#4.flac",
        include_bytes!("../samples/dulcimer_C#4.flac"),
    ),
    (
        "dulcimer_C5.flac",
        include_bytes!("../samples/dulcimer_C5.flac"),
    ),
    (
        "dulcimer_D4.flac",
        include_bytes!("../samples/dulcimer_D4.flac"),
    ),
    (
        "dulcimer_D5.flac",
        include_bytes!("../samples/dulcimer_D5.flac"),
    ),
    (
        "dulcimer_E4.flac",
        include_bytes!("../samples/dulcimer_E4.flac"),
    ),
    (
        "dulcimer_F#4.flac",
        include_bytes!("../samples/dulcimer_F#4.flac"),
    ),
    (
        "dulcimer_G4.flac",
        include_bytes!("../samples/dulcimer_G4.flac"),
    ),
    (
        "rhodes_A#1.flac",
        include_bytes!("../samples/rhodes_A#1.flac"),
    ),
    (
        "rhodes_A#5.flac",
        include_bytes!("../samples/rhodes_A#5.flac"),
    ),
    (
        "rhodes_C#2.flac",
        include_bytes!("../samples/rhodes_C#2.flac"),
    ),
    (
        "rhodes_C#3.flac",
        include_bytes!("../samples/rhodes_C#3.flac"),
    ),
    (
        "rhodes_C#6.flac",
        include_bytes!("../samples/rhodes_C#6.flac"),
    ),
    (
        "rhodes_D#5.flac",
        include_bytes!("../samples/rhodes_D#5.flac"),
    ),
    (
        "rhodes_E1.flac",
        include_bytes!("../samples/rhodes_E1.flac"),
    ),
    (
        "rhodes_E2.flac",
        include_bytes!("../samples/rhodes_E2.flac"),
    ),
    (
        "rhodes_E5.flac",
        include_bytes!("../samples/rhodes_E5.flac"),
    ),
    (
        "rhodes_G#2.flac",
        include_bytes!("../samples/rhodes_G#2.flac"),
    ),
    (
        "rhodes_G#5.flac",
        include_bytes!("../samples/rhodes_G#5.flac"),
    ),
];

/// Returns the embedded sample bytes for an exact (case-sensitive) name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded samples; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 748771;

    #[test]
    fn inventory_matches_packaged_samples() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| matches!(p.extension().and_then(OsStr::to_str), Some("wav" | "flac")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_bank_file_with_the_expected_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a sample");
            let riff = &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WAVE";
            let flac = &bytes[..4] == b"fLaC";
            assert!(riff || flac, "{name} is neither RIFF/WAVE nor FLAC");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
