#!/usr/bin/env python3
"""Generate a `src/lib.rs` for a ferrosintesis sample crate from its `samples/*.wav`.

Every sample crate ships the same shape: a static `SAMPLES` table of
`(name, include_bytes!(...))`, a `get()` lookup, and two parity tests
(`inventory_matches_packaged_wavs`, aggregate-bytes). Hand-writing a 54-entry
table per crate is tedious and error-prone, so this emits it from the actual files
on disk. FILE_COUNT and EXPECTED_BYTES are computed from the directory, so the
tests are self-consistent by construction.

    python gen_crate_lib.py ../../crates/ferrosintesis-samples-vcsl-steinway \
        --doc "Embedded CC0 VCSL Steinway-B grand samples (GM0 alternate bank 1)."
"""
import os
import sys


def main():
    crate = sys.argv[1]
    doc = "Embedded ferrosintesis sample bank."
    a = sys.argv[2:]
    i = 0
    while i < len(a):
        if a[i] == "--doc":
            doc = a[i + 1]; i += 2
        else:
            raise SystemExit(f"unknown arg {a[i]}")
    samples_dir = os.path.join(crate, "samples")
    names = sorted(f for f in os.listdir(samples_dir) if f.endswith(".wav"))
    if not names:
        raise SystemExit(f"no .wav files in {samples_dir}")
    total = sum(os.path.getsize(os.path.join(samples_dir, n)) for n in names)

    lines = []
    lines.append(f"//! {doc}")
    lines.append("//!")
    lines.append("//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the")
    lines.append("//! committed `samples/*.wav`; consumers normally reach it through")
    lines.append("//! `ferrosintesis`. Attribution/licence: see `NOTICE` / `PROVENANCE.md`.")
    lines.append("")
    lines.append("#![forbid(unsafe_code)]")
    lines.append("")
    lines.append("/// Number of WAV files embedded in this package.")
    lines.append(f"pub const FILE_COUNT: usize = {len(names)};")
    lines.append("")
    lines.append("static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [")
    for n in names:
        lines.append(f'    ("{n}", include_bytes!("../samples/{n}")),')
    lines.append("];")
    lines.append("")
    lines.append("/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.")
    lines.append("pub fn get(name: &str) -> Option<&'static [u8]> {")
    lines.append("    SAMPLES")
    lines.append("        .iter()")
    lines.append("        .find(|(candidate, _)| *candidate == name)")
    lines.append("        .map(|(_, bytes)| *bytes)")
    lines.append("}")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    use super::*;")
    lines.append("    use std::ffi::OsStr;")
    lines.append("    use std::fs;")
    lines.append("    use std::path::Path;")
    lines.append("")
    lines.append("    // Aggregate byte size of the embedded WAVs; regenerate with")
    lines.append("    // gen_crate_lib.py and re-pin if the bank changes.")
    lines.append(f"    const EXPECTED_BYTES: usize = {total};")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn inventory_matches_packaged_wavs() {")
    lines.append('        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");')
    lines.append("        let mut packaged: Vec<String> = fs::read_dir(samples_dir)")
    lines.append('            .expect("sample directory must exist")')
    lines.append('            .map(|e| e.expect("readable entry").path())')
    lines.append('            .filter(|p| p.extension() == Some(OsStr::new("wav")))')
    lines.append('            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())')
    lines.append("            .collect();")
    lines.append("        packaged.sort();")
    lines.append(
        "        let mut embedded: Vec<String> = "
        "SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();"
    )
    lines.append("        embedded.sort();")
    lines.append("        assert_eq!(packaged.len(), FILE_COUNT);")
    lines.append("        assert_eq!(embedded, packaged);")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {")
    lines.append("        assert_eq!(")
    lines.append("            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),")
    lines.append("            EXPECTED_BYTES")
    lines.append("        );")
    lines.append("        for (name, bytes) in SAMPLES {")
    lines.append('            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");')
    lines.append('            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");')
    lines.append('            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");')
    lines.append("            assert_eq!(get(name), Some(bytes));")
    lines.append("        }")
    lines.append('        assert_eq!(get("missing.wav"), None);')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    out = os.path.join(crate, "src", "lib.rs")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: {len(names)} files, {total} bytes")


if __name__ == "__main__":
    main()
