#!/usr/bin/env python3
"""Generate a `src/lib.rs` for a ferrosintesis sample crate from its `samples/*.wav`.

Every sample crate ships the same shape: a static `SAMPLES` table of
`(name, include_bytes!(...))`, a `get()` lookup, and two parity tests
(`inventory_matches_packaged_wavs`, aggregate-bytes). Hand-writing a 54-entry
table per crate is tedious and error-prone, so this emits it from the actual files
on disk. FILE_COUNT and EXPECTED_BYTES are computed from the directory, so the
tests are self-consistent by construction.

    python gen_crate_lib.py ../../crates/ferrosintesis-samples-vcsl-steinway \
        --doc "Embedded CC0 VCSL Steinway-B grand samples (GM0 alternate bank 3)."
"""
import os
import subprocess
import sys


LEGAL_DOC_NAMES = ("LICENSE-CC0", "LICENSE-MIT", "NOTICE", "PROVENANCE.md")


def shipped_docs(crate):
    """Return legal/provenance files both present and named by Cargo packaging."""
    manifest_path = os.path.join(crate, "Cargo.toml")
    with open(manifest_path, encoding="utf-8") as f:
        manifest = f.read()
    docs = [
        name
        for name in LEGAL_DOC_NAMES
        if os.path.isfile(os.path.join(crate, name)) and name in manifest
    ]
    if not docs:
        raise ValueError(
            f"{crate} packages no legal/provenance document; "
            "fix Cargo.toml before generating"
        )
    return docs


def legal_doc_line(crate):
    """Render the generated crate-level legal/provenance pointer."""
    docs = " / ".join(f"`{name}`" for name in shipped_docs(crate))
    return f"//! `ferrosintesis`. Licence/provenance: see {docs}."


def read_aliases(crate, physical_names):
    """Read optional `ALIASES` rows as `logical-name canonical-physical-name`."""
    path = os.path.join(crate, "ALIASES")
    if not os.path.isfile(path):
        return {}
    physical = set(physical_names)
    aliases = {}
    with open(path, encoding="utf-8") as f:
        for number, raw in enumerate(f, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            if len(fields) != 2:
                raise ValueError(f"{path}:{number}: expected ALIAS CANONICAL")
            alias, canonical = fields
            if alias in physical:
                raise ValueError(f"{path}:{number}: alias {alias} is also a physical WAV")
            if canonical not in physical:
                raise ValueError(
                    f"{path}:{number}: canonical target {canonical} is not a physical WAV"
                )
            if alias in aliases:
                raise ValueError(f"{path}:{number}: duplicate alias {alias}")
            aliases[alias] = canonical
    return aliases


def main():
    crate = sys.argv[1]
    doc = "Embedded ferrosintesis sample bank."
    a = sys.argv[2:]
    i = 0
    while i < len(a):
        if a[i] == "--doc":
            doc = a[i + 1]; i += 2
        else:
            raise SystemExit(f"unknown arg {a[i]}")
    samples_dir = os.path.join(crate, "samples")
    names = sorted(f for f in os.listdir(samples_dir) if f.endswith(".wav"))
    if not names:
        raise SystemExit(f"no .wav files in {samples_dir}")
    aliases = read_aliases(crate, names)
    total = sum(os.path.getsize(os.path.join(samples_dir, n)) for n in names)
    lines = []
    lines.append(f"//! {doc}")
    lines.append("//!")
    lines.append("//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the")
    lines.append("//! committed `samples/*.wav`; consumers normally reach it through")
    try:
        lines.append(legal_doc_line(crate))
    except ValueError as error:
        raise SystemExit(str(error)) from error
    lines.append("")
    lines.append("#![forbid(unsafe_code)]")
    lines.append("")
    lines.append("/// Number of WAV files embedded in this package.")
    lines.append(f"pub const FILE_COUNT: usize = {len(names)};")
    if aliases:
        lines.append("")
        lines.append("/// Number of exact logical names accepted, including aliases.")
        lines.append(f"pub const LOGICAL_FILE_COUNT: usize = {len(names) + len(aliases)};")
    lines.append("")
    lines.append("static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [")
    for n in names:
        lines.append(f'    ("{n}", include_bytes!("../samples/{n}")),')
    lines.append("];")
    if aliases:
        lines.append("")
        lines.append(f"static ALIASES: [(&str, &str); {len(aliases)}] = [")
        for alias, canonical in sorted(aliases.items()):
            lines.append(f'    ("{alias}", "{canonical}"),')
        lines.append("];")
    lines.append("")
    lines.append("/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.")
    lines.append("pub fn get(name: &str) -> Option<&'static [u8]> {")
    if aliases:
        lines.append("    let name = ALIASES")
        lines.append("        .iter()")
        lines.append("        .find(|(alias, _)| *alias == name)")
        lines.append("        .map_or(name, |(_, canonical)| *canonical);")
    lines.append("    SAMPLES")
    lines.append("        .iter()")
    lines.append("        .find(|(candidate, _)| *candidate == name)")
    lines.append("        .map(|(_, bytes)| *bytes)")
    lines.append("}")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    use super::*;")
    lines.append("    use std::ffi::OsStr;")
    lines.append("    use std::fs;")
    lines.append("    use std::path::Path;")
    lines.append("")
    lines.append("    // Aggregate byte size of the embedded WAVs; regenerate with")
    lines.append("    // gen_crate_lib.py and re-pin if the bank changes.")
    lines.append(f"    const EXPECTED_BYTES: usize = {total};")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn inventory_matches_packaged_wavs() {")
    lines.append('        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");')
    lines.append("        let mut packaged: Vec<String> = fs::read_dir(samples_dir)")
    lines.append('            .expect("sample directory must exist")')
    lines.append('            .map(|e| e.expect("readable entry").path())')
    lines.append('            .filter(|p| p.extension() == Some(OsStr::new("wav")))')
    lines.append('            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())')
    lines.append("            .collect();")
    lines.append("        packaged.sort();")
    lines.append(
        "        let mut embedded: Vec<String> = "
        "SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();"
    )
    lines.append("        embedded.sort();")
    lines.append("        assert_eq!(packaged.len(), FILE_COUNT);")
    lines.append("        assert_eq!(embedded, packaged);")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {")
    lines.append("        assert_eq!(")
    lines.append("            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),")
    lines.append("            EXPECTED_BYTES")
    lines.append("        );")
    lines.append("        for (name, bytes) in SAMPLES {")
    lines.append('            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");')
    lines.append('            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");')
    lines.append('            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");')
    lines.append("            assert_eq!(get(name), Some(bytes));")
    lines.append("        }")
    lines.append('        assert_eq!(get("missing.wav"), None);')
    lines.append("    }")
    if aliases:
        lines.append("")
        lines.append("    #[test]")
        lines.append("    fn aliases_resolve_without_duplicate_physical_payloads() {")
        lines.append("        assert_eq!(LOGICAL_FILE_COUNT, FILE_COUNT + ALIASES.len());")
        lines.append("        let declared: Vec<(&str, &str)> = include_str!(\"../ALIASES\")")
        lines.append("            .lines()")
        lines.append("            .filter_map(|line| {")
        lines.append("                let line = line.trim();")
        lines.append("                if line.is_empty() || line.starts_with('#') {")
        lines.append("                    return None;")
        lines.append("                }")
        lines.append("                let mut fields = line.split_whitespace();")
        lines.append("                let pair = (fields.next().unwrap(), fields.next().unwrap());")
        lines.append("                assert!(fields.next().is_none(), \"malformed alias row {line}\");")
        lines.append("                Some(pair)")
        lines.append("            })")
        lines.append("            .collect();")
        lines.append("        assert_eq!(declared, ALIASES);")
        lines.append("        for (alias, canonical) in ALIASES {")
        lines.append("            assert_eq!(get(alias), get(canonical), \"alias {alias}\");")
        lines.append("        }")
        lines.append("        for (left, (left_name, left_bytes)) in")
        lines.append("            SAMPLES.iter().copied().enumerate()")
        lines.append("        {")
        lines.append("            for (right_name, right_bytes) in")
        lines.append("                SAMPLES.iter().copied().skip(left + 1)")
        lines.append("            {")
        lines.append("                assert!(")
        lines.append("                    left_bytes != right_bytes,")
        lines.append("                    \"undeclared duplicate payloads: {} and {}\",")
        lines.append("                    left_name,")
        lines.append("                    right_name")
        lines.append("                );")
        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
    lines.append("}")
    lines.append("")

    out = os.path.join(crate, "src", "lib.rs")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))

    # rustfmt the result rather than trying to reproduce its heuristics here. An entry is
    # `2*len(name) + 35` chars wide, so any WAV name over 12 characters exceeds rustfmt's
    # 60-char fn_call_width and gets wrapped; a one-file crate goes the other way and gets
    # folded onto one line. Emitting either form by hand is wrong for the other case, and
    # the mismatch only ever surfaced at the integration gate's `cargo fmt --all --check`.
    try:
        subprocess.run(["rustfmt", "--edition", "2021", out], check=True)
    except FileNotFoundError:
        raise SystemExit(
            f"wrote {out}, but `rustfmt` is not on PATH — the generated table is not "
            "fmt-clean and will fail `cargo fmt --all --check`. Install it with "
            "`rustup component add rustfmt`, then re-run."
        )

    print(f"wrote {out}: {len(names)} files, {total} bytes")


if __name__ == "__main__":
    main()
