//! Embedded owner-recorded CC0 mandolin pluck onsets for ferrosintesis (GM 25 steel guitar, bank LSB 96 - the XG Mandolin cell). Ten pitch zones x four round robins.
//!
//! Generated by `tools/ferrosintesis-samples/gen_crate_lib.py` from the
//! committed `samples/*.wav`; consumers normally reach it through `ferrosintesis`.
//! Licence/provenance: see `LICENSE-CC0` / `PROVENANCE.md`.

#![forbid(unsafe_code)]

/// Number of WAV files embedded in this package.
pub const FILE_COUNT: usize = 40;

static SAMPLES: [(&str, &[u8]); FILE_COUNT] = [
    (
        "mandolin_A4_rr1.wav",
        include_bytes!("../samples/mandolin_A4_rr1.wav"),
    ),
    (
        "mandolin_A4_rr2.wav",
        include_bytes!("../samples/mandolin_A4_rr2.wav"),
    ),
    (
        "mandolin_A4_rr3.wav",
        include_bytes!("../samples/mandolin_A4_rr3.wav"),
    ),
    (
        "mandolin_A4_rr4.wav",
        include_bytes!("../samples/mandolin_A4_rr4.wav"),
    ),
    (
        "mandolin_A5_rr1.wav",
        include_bytes!("../samples/mandolin_A5_rr1.wav"),
    ),
    (
        "mandolin_A5_rr2.wav",
        include_bytes!("../samples/mandolin_A5_rr2.wav"),
    ),
    (
        "mandolin_A5_rr3.wav",
        include_bytes!("../samples/mandolin_A5_rr3.wav"),
    ),
    (
        "mandolin_A5_rr4.wav",
        include_bytes!("../samples/mandolin_A5_rr4.wav"),
    ),
    (
        "mandolin_C4_rr1.wav",
        include_bytes!("../samples/mandolin_C4_rr1.wav"),
    ),
    (
        "mandolin_C4_rr2.wav",
        include_bytes!("../samples/mandolin_C4_rr2.wav"),
    ),
    (
        "mandolin_C4_rr3.wav",
        include_bytes!("../samples/mandolin_C4_rr3.wav"),
    ),
    (
        "mandolin_C4_rr4.wav",
        include_bytes!("../samples/mandolin_C4_rr4.wav"),
    ),
    (
        "mandolin_D4_rr1.wav",
        include_bytes!("../samples/mandolin_D4_rr1.wav"),
    ),
    (
        "mandolin_D4_rr2.wav",
        include_bytes!("../samples/mandolin_D4_rr2.wav"),
    ),
    (
        "mandolin_D4_rr3.wav",
        include_bytes!("../samples/mandolin_D4_rr3.wav"),
    ),
    (
        "mandolin_D4_rr4.wav",
        include_bytes!("../samples/mandolin_D4_rr4.wav"),
    ),
    (
        "mandolin_D5_rr1.wav",
        include_bytes!("../samples/mandolin_D5_rr1.wav"),
    ),
    (
        "mandolin_D5_rr2.wav",
        include_bytes!("../samples/mandolin_D5_rr2.wav"),
    ),
    (
        "mandolin_D5_rr3.wav",
        include_bytes!("../samples/mandolin_D5_rr3.wav"),
    ),
    (
        "mandolin_D5_rr4.wav",
        include_bytes!("../samples/mandolin_D5_rr4.wav"),
    ),
    (
        "mandolin_D6_rr1.wav",
        include_bytes!("../samples/mandolin_D6_rr1.wav"),
    ),
    (
        "mandolin_D6_rr2.wav",
        include_bytes!("../samples/mandolin_D6_rr2.wav"),
    ),
    (
        "mandolin_D6_rr3.wav",
        include_bytes!("../samples/mandolin_D6_rr3.wav"),
    ),
    (
        "mandolin_D6_rr4.wav",
        include_bytes!("../samples/mandolin_D6_rr4.wav"),
    ),
    (
        "mandolin_E5_rr1.wav",
        include_bytes!("../samples/mandolin_E5_rr1.wav"),
    ),
    (
        "mandolin_E5_rr2.wav",
        include_bytes!("../samples/mandolin_E5_rr2.wav"),
    ),
    (
        "mandolin_E5_rr3.wav",
        include_bytes!("../samples/mandolin_E5_rr3.wav"),
    ),
    (
        "mandolin_E5_rr4.wav",
        include_bytes!("../samples/mandolin_E5_rr4.wav"),
    ),
    (
        "mandolin_E6_rr1.wav",
        include_bytes!("../samples/mandolin_E6_rr1.wav"),
    ),
    (
        "mandolin_E6_rr2.wav",
        include_bytes!("../samples/mandolin_E6_rr2.wav"),
    ),
    (
        "mandolin_E6_rr3.wav",
        include_bytes!("../samples/mandolin_E6_rr3.wav"),
    ),
    (
        "mandolin_E6_rr4.wav",
        include_bytes!("../samples/mandolin_E6_rr4.wav"),
    ),
    (
        "mandolin_G3_rr1.wav",
        include_bytes!("../samples/mandolin_G3_rr1.wav"),
    ),
    (
        "mandolin_G3_rr2.wav",
        include_bytes!("../samples/mandolin_G3_rr2.wav"),
    ),
    (
        "mandolin_G3_rr3.wav",
        include_bytes!("../samples/mandolin_G3_rr3.wav"),
    ),
    (
        "mandolin_G3_rr4.wav",
        include_bytes!("../samples/mandolin_G3_rr4.wav"),
    ),
    (
        "mandolin_G4_rr1.wav",
        include_bytes!("../samples/mandolin_G4_rr1.wav"),
    ),
    (
        "mandolin_G4_rr2.wav",
        include_bytes!("../samples/mandolin_G4_rr2.wav"),
    ),
    (
        "mandolin_G4_rr3.wav",
        include_bytes!("../samples/mandolin_G4_rr3.wav"),
    ),
    (
        "mandolin_G4_rr4.wav",
        include_bytes!("../samples/mandolin_G4_rr4.wav"),
    ),
];

/// Returns the embedded WAV bytes for an exact (case-sensitive) file name.
pub fn get(name: &str) -> Option<&'static [u8]> {
    SAMPLES
        .iter()
        .find(|(candidate, _)| *candidate == name)
        .map(|(_, bytes)| *bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::fs;
    use std::path::Path;

    // Aggregate byte size of the embedded WAVs; regenerate with
    // gen_crate_lib.py and re-pin if the bank changes.
    const EXPECTED_BYTES: usize = 3205120;

    #[test]
    fn inventory_matches_packaged_wavs() {
        let samples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("samples");
        let mut packaged: Vec<String> = fs::read_dir(samples_dir)
            .expect("sample directory must exist")
            .map(|e| e.expect("readable entry").path())
            .filter(|p| p.extension() == Some(OsStr::new("wav")))
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        packaged.sort();
        let mut embedded: Vec<String> = SAMPLES.iter().map(|(n, _)| (*n).to_owned()).collect();
        embedded.sort();
        assert_eq!(packaged.len(), FILE_COUNT);
        assert_eq!(embedded, packaged);
    }

    #[test]
    fn every_sample_is_a_nonempty_wav_with_the_expected_aggregate_size() {
        assert_eq!(
            SAMPLES.iter().map(|(_, b)| b.len()).sum::<usize>(),
            EXPECTED_BYTES
        );
        for (name, bytes) in SAMPLES {
            assert!(bytes.len() >= 12, "{name} is too short to be a WAV");
            assert_eq!(&bytes[..4], b"RIFF", "{name} has no RIFF header");
            assert_eq!(&bytes[8..12], b"WAVE", "{name} has no WAVE signature");
            assert_eq!(get(name), Some(bytes));
        }
        assert_eq!(get("missing.wav"), None);
    }
}
